apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  namespace: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
        - name: python-container
          image: szgyuval123/gitops-repo:python-app-16-ad8049b3f6a0ed354cb577d05bfb61a96cf45a7a
          ports:
            - containerPort: 5000
