apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  namespace: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
        - name: python-container
          image: szgyuval123/gitops-repo:python-app-19-3cf77fb9fa774f3887dff1df47ff981a1c280c59
          ports:
            - containerPort: 5000
