apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  namespace: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
        - name: python-container
          image: szgyuval123/gitops-repo:python-app-8-006154380cc9f148996d0e7424a097e581c6798f
          ports:
            - containerPort: 5000
