apiVersion: v1
kind: Service
metadata:
  name: python-service
  namespace: python-app
spec:
  selector:
    app: python
  type: NodePort
  ports:
    - targetPort: 8000
      port: 8000
      nodePort: 30005
      protocol: TCP